[phases.setup]
nixPkgs = ["nodejs-22_x", "pnpm"]

[phases.install]
cmds = [
  "pnpm config set node-linker hoisted",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "node .output/server/index.mjs"
